using System.Collections.Generic;

namespace vima.domain
{
    /// <summary>
    /// Provides mechanisms for converting a mapping source to and from informatin stored in a file format.
    /// </summary>
    public interface ISourceTranslator
    {
        /// <summary>
        /// Retrieves the lines which should head the document generated via this implementation.
        /// </summary>
        /// <param name="mappings"></param>
        /// <returns></returns>
        string[] GetHeaderInformation(MappingsSource mappings);
        /// <summary>
        /// Retrieves the lines should end the document generated by the implementation
        /// </summary>
        /// <param name="mappings"></param>
        /// <returns></returns>
        string[] GetFooter(MappingsSource mappings);

        IEnumerable<string> FormatMappings(MappingsSource mappings);
        IEnumerable<Mapping> Parse(IEnumerable<string> mappings);
    }
}
